services:
  tournament_engine:
    build: .
    container_name: tournament_engine
    env_file:
      - .env
    networks:
      - rabbitmq.docker

networks:
  rabbitmq.docker:
    name: rabbitmq.docker
    external: true