name: Build a shared .env

on:
  workflow_call:

jobs:
  create_env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build env file
        shell: bash
        run: |
          touch ./.env.art
          VER=$(cat VERSION)
          echo "VERSION=$VER" >> ./.env.art
          echo "APP=tournament_engine" >> ./.env.art

      - name: Upload env artifact
        uses: actions/upload-artifact@v4
        with:
          name: env
          path: ./.env.art
